const medicines = [
    { name: 'Amoxicillin', category: 'Antibiotic' },
    { name: 'Aspirin', category: 'Pain Reliever' },
      { name: 'Albuterol', category: 'Respiratory' },
      { name: 'ADHD', category: 'Neurology' },
      { name: 'Acne', category: 'Dermatology' },
      { name: 'Alcohol Addiction', category: 'Addiction Medicine' },
      { name: 'Allergies', category: 'Immunology' },
      { name: 'Alzheimer', category: 'Neurology' },
      { name: 'Amoebiasis', category: 'Infectious Disease' },
      { name: 'Anaemia', category: 'Hematology' },
      { name: 'Anaesthesia - Local', category: 'Anesthesiology' },
      { name: 'Anaesthesia General', category: 'Anesthesiology' },
      { name: 'Anal Fissure', category: 'Gastroenterology' },
      { name: 'Angina', category: 'Cardiology' },
      { name: 'Anti allergic', category: 'Immunology' },
      { name: 'Anti-Scar', category: 'Dermatology' },
      { name: 'Antibiotic', category: 'Infectious Disease' },
      { name: 'Anxiety', category: 'Psychiatry' },
      { name: 'Apnea', category: 'Respiratory' },
      { name: 'Appetite', category: 'Nutrition' },
      { name: 'Arrhythmiasis', category: 'Cardiology' },
      { name: 'Arthritis', category: 'Rheumatology' },
      { name: 'Asthma/COPD', category: 'Respiratory' },
      { name: 'Atopic Dermatitis(Eczema)', category: 'Dermatology' },
      { name: 'Auto Immune Disease', category: 'Immunology' },
      { name: 'Ayurvedic Medicine', category: 'Alternative Medicine' },
      { name: 'Bacterial Infections', category: 'Infectious Disease' },
      { name: 'Bladder And Prostate Disorders', category: 'Urology' },
      { name: 'Bleeding Disorders', category: 'Hematology' },
      { name: 'Blood Clot', category: 'Cardiology' },
      { name: 'Bone Metabolism', category: 'Endocrinology' },
      { name: 'Burns', category: 'Emergency Medicine' },
    { name: 'Benadryl', category: 'Allergy' },
    { name: 'CNS stimulants', category: 'Neurology' },
    { name: 'Cancer Oncology', category: 'Oncology' },
    { name: 'Cardiac Arrest', category: 'Cardiology' },
    { name: 'Cerebral Ischemic Stroke', category: 'Neurology' },
    { name: 'Cholelithiasis/Gall Stones', category: 'Gastroenterology' },
    { name: 'Cleanser', category: 'Personal Care' },
    { name: 'Colon Cleanser', category: 'Gastroenterology' },
    { name: 'Constipation', category: 'Gastroenterology' },
    { name: 'Contraception', category: 'Reproductive Health' },
    { name: 'Cough And Cold', category: 'Respiratory' },
    { name: 'Crack', category: 'Substance Abuse' },
    { name: 'Calamine Lotion', category: 'Skin Care' },
    { name: 'Dandruff', category: 'Skin Care' },
    { name: 'Denture Adhesive', category: 'Dental Care' },
    { name: 'Depression', category: 'Psychiatry' },
    { name: 'Dewormer', category: 'Parasitology' },
    { name: 'Diabetes', category: 'Endocrinology' },
    { name: 'Diagnostic', category: 'Medical Tests' },
  
  
  
    { name: 'Diarrhoea', category: 'Gastroenterology' },
    { name: 'Dietary Management', category: 'Nutrition' },
    { name: 'Digestion', category: 'Gastroenterology' },
    { name: 'Dry Eye', category: 'Ophthalmology' },
    { name: 'Dry Skin', category: 'Dermatology' },
      { name: 'Ear Conditions', category: 'Ear' },
      { name: 'Ectoparasiticide', category: 'Ectoparasiticide' },
      { name: 'Electrolytes', category: 'Electrolytes' },
      { name: 'Epilepsy/Convulsion', category: 'Neurology' },
      { name: 'Eye Infections', category: 'Ophthalmology' },
      { name: 'Eye conditions', category: 'Ophthalmology' },
      { name: 'Fever', category: 'General Medicine' },
      { name: 'Fungal', category: 'Dermatology' },
      { name: 'Fungal Infections', category: 'Infectious Disease' },
      { name: 'Gastro Intestinal Motility Disorders', category: 'Gastroenterology' },
      { name: 'General-P', category: 'General Medicine' },
      { name: 'Glaucoma', category: 'Ophthalmology' },
      { name: 'Gout', category: 'Rheumatology' },
      { name: 'H.Pylori Infection', category: 'Infectious Disease' },
      { name: 'Haematopoiesis', category: 'Hematology' },
      { name: 'Haemorrhoid', category: 'Gastroenterology' },
      { name: 'Hair Color - P', category: 'Personal Care' },
      { name: 'Hair Loss', category: 'Dermatology' },
      { name: 'Head Lice', category: 'Dermatology' },
      { name: 'Heart Failure', category: 'Cardiology' },
      { name: 'Hepatitis B Infection', category: 'Infectious Disease' },
      { name: 'High Cholesterol', category: 'Cardiology' },
      { name: 'Hirsutism', category: 'Dermatology' },
      { name: 'Hormonal Therapy', category: 'Endocrinology' },
      { name: 'Hyperpigmentation', category: 'Dermatology' },
      { name: 'Hypertension', category: 'Cardiology' },
      { name: 'Hyperthyroidism', category: 'Endocrinology' },
      { name: 'Hypnosis', category: 'Psychiatry' },
      { name: 'Hyponatremia', category: 'Nephrology' },
      { name: 'Hypotension', category: 'Cardiology' },
      { name: 'Hypothyroidism', category: 'Endocrinology' },
      { name: 'Idiopathic Pulmonary Fibrosis', category: 'Pulmonology' },
      { name: 'Immune Sera', category: 'Immunology' },
      { name: 'Immune Suppression', category: 'Immunology' },
      { name: 'Immunoglobulins', category: 'Immunology' },
      { name: 'Impotence/Erectile Dysfunction (Ed)', category: 'Urology' },
      { name: 'Infection', category: 'Infectious Disease' },
      { name: 'Inhaler/Nebulizer', category: 'Respiratory' },
      { name: 'Insulin Pen (Device)', category: 'Endocrinology' },
      { name: 'Intermittent Claudication', category: 'Cardiology' },
  
  
      { name: 'Iron Supplement/Anaemia', category: 'Hematology' },
      { name: 'Itching/Dry Skin', category: 'Dermatology' },
      { name: 'Kidney Disease/Stones', category: 'Nephrology' },
      { name: 'LYMPHOEDEMA', category: 'Lymphology' },
      { name: 'Leprosy', category: 'Infectious Disease' },
      { name: 'Liver Disease', category: 'Hepatology' },
      { name: 'Liver Supplement', category: 'Hepatology' },
      { name: 'Lubrication', category: 'Personal Care' },
      { name: 'Malarial', category: 'Infectious Disease' },
      { name: 'Melasma', category: 'Dermatology' },
      { name: 'Migraine', category: 'Neurology' },
      { name: 'Mucolytic Agent', category: 'Respiratory' },
      { name: 'Multiple Sclerosis', category: 'Neurology' },
      { name: 'Muscle Cramps/Spasticity', category: 'Neurology' },
      { name: 'Muscle Spasm', category: 'Neurology' },
      { name: 'Myasthenia Gravis', category: 'Neurology' },
      { name: 'Mydriasis', category: 'Ophthalmology' },
      { name: 'Nappy Rash', category: 'Dermatology' },
      { name: 'Nasal Congestion', category: 'ENT' },
      { name: 'Neuropathic Pain', category: 'Neurology' },
      { name: 'Nootropics And Neurotrophics', category: 'Neurology' },
      { name: 'Obese', category: 'Endocrinology' },
      { name: 'Obesity', category: 'Endocrinology' },
      { name: 'Oral Care - P', category: 'Dental' },
      { name: 'Osteoporosis', category: 'Rheumatology' },
      { name: 'Pain relief', category: 'Pain Management' },
      { name: 'Parasitic Worms', category: 'Parasitology' },
      { name: 'Parkinsonism', category: 'Neurology' },
      { name: 'Patanjali Ayurvedic', category: 'Ayurvedic' },
      { name: 'Pen (Device)', category: 'Medical Device' },
      { name: 'Peripheral Hypertension', category: 'Cardiology' },
  
  
  
      { name: 'Peripheral Vascular Disease', category: 'Cardiology' },
      { name: 'Poisoning/Overdose', category: 'Toxicology' },
      { name: 'Polycystic ovary syndrome(PCOS)', category: 'Gynecology' },
      { name: 'Pregnancy Testing Kit', category: 'Obstetrics' },
      { name: 'Premature Ejaculation', category: 'Urology' },
      { name: 'Psoriasis', category: 'Dermatology' },
      { name: 'Psoriasis/Seborrhea/Ichthyosis', category: 'Dermatology' },
      { name: 'Psychosis', category: 'Psychiatry' },
      { name: 'Pulmonary Arterial Hypertension (Pah)', category: 'Pulmonology' },
      { name: 'Rabies', category: 'Infectious Disease' },
      { name: 'Rheumatoid Arthritis', category: 'Rheumatology' },
      { name: 'Sanitizer', category: 'Personal Care' },
      { name: 'Scabies', category: 'Dermatology' },
      { name: 'Scar', category: 'Dermatology' },
      { name: 'Schizophrenia', category: 'Psychiatry' },
      { name: 'Skin Infections', category: 'Dermatology' },
      { name: 'Sleep Disorder (Insomnia)', category: 'Psychiatry' },
      { name: 'Smoking cessation', category: 'Respiratory' },
      { name: 'Stretch Marks', category: 'Dermatology' },
      { name: 'Sun Protectors', category: 'Dermatology' },
      { name: 'Sunscreen Preparations', category: 'Dermatology' },
      { name: 'Supplements', category: 'Nutrition' },
      { name: 'Surgicals', category: 'Surgery' },
      { name: 'Syringe', category: 'Medical Device' },
      { name: 'Targeted Cancer Therapy', category: 'Oncology' },
      { name: 'Tetanus', category: 'Infectious Disease' },
      { name: 'Thrombotic Disorder', category: 'Hematology' },
      { name: 'Tuberculosis (Tb)', category: 'Infectious Disease' },
      { name: 'Ulcer/Reflux/Flatulence', category: 'Gastroenterology' },
      { name: 'Ulcerative Colitis/Bowel Inflammatory Disease', category: 'Gastroenterology' },
      { name: 'Urinary Retention', category: 'Urology' },
      { name: 'Uterus Conditions', category: 'Obstetrics' },
      { name: 'Uti Infections', category: 'Infectious Disease' },
      { name: 'Vaccines', category: 'Immunology' },
      { name: 'Vaginal Capsules', category: 'Gynecology' },
      { name: 'Vaginal Conditions', category: 'Gynecology' },
      { name: 'Varicose Veins', category: 'Vascular' },
      { name: 'Vertigo', category: 'Neurology' },
      { name: 'Veterinary-Pharma', category: 'Veterinary' },
      { name: 'Viral infections', category: 'Infectious Disease' },
      { name: 'Vitamin B12', category: 'Nutrition' },
      { name: 'Vitamin C/Supplements', category: 'Nutrition' },
      { name: 'Vitamin D3', category: 'Nutrition' },
      { name: 'Vitamin E', category: 'Nutrition' },
      { name: 'Vitiligo', category: 'Dermatology' },
      { name: 'Vomitting/Emesis', category: 'Gastroenterology' },
      { name: 'Warts/Calluses/Other Skin Lesion', category: 'Dermatology' },
      { name: 'Weight Loss (Pharma)', category: 'Endocrinology' },
      { name: 'Wound Care', category: 'General Medicine' },
      { name: 'Wrinkle/Anti Ageing', category: 'Dermatology' }
    
  ];